### PR TITLE
Adding map

### PR DESCRIPTION
**Pull request by ajakubo1**
This is the pull request which adds a possibility of showing map and additional elements (I've prepared and used as an example 4 markers).

I'm missing here:

- [ ] fetching data from server (+ I didn't add any ``fetch`` polyfill)
- [x] there are a lot of components missing :/
- [x] I didn't have time to add tests for actions/reducers
- [ ] Would be neat to mock some data if back-end is not avaliable
- [ ] We should add logic which would allow us to decide which marker on the map should be displayed with which pollution level

---
This change is [Reviewable](https://reviewable.io/reviews/enviromonitor/enviromonitorfrontend/15)

### CODE REVIEW

**Comment by lechup** [comment]
Generallly :lgtm:, have You seen my markup here: https://github.com/EnviroMonitor/EnviroMonitorFrontend/issues/3#issuecomment-268774711?

Have a look at whole discussion there.

---

Reviewed 17 of 21 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[webpack.config.js, line 9 at r2](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KaGbaTQ8yGc5TMbCUvb:-KaGbaTQ8yGc5TMbCUvc:b-yvyy1g) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/79c28d7f301db930c0737cc06fd6ade527cb4c27/webpack.config.js#L9)):*
> ```JavaScript
> const PATHS = {
>     app: path.join(__dirname, 'app'),
>     styles: [
> ```

This is correct way of doing it? I'm using import './node_modules/whatever/file.css' and it is magicaly added by css-loader.

The same with images only by file loader?

```
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                query: {
                    presets: ['es2015', 'react', 'stage-0']
                }
            },
            {
                test: /\.less$/,
                loader: 'style!css!postcss-loader!less-loader',
            },
            {
                test: /\.scss/,
                loader: 'style!css!postcss-loader!sass-loader',
            },
            {
                test: /\.css$/,
                loader: 'style!css!postcss-loader',
            },
            {
              test: /\.(png|jpg|gif|svg)$/,
              loader: "file-loader?name=[path][name].[ext]?[hash]"
            }
        ]
    },
```

Should I read something? :)

---

*[app/helpers/mapMarkers.js, line 41 at r2](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KaGgd26eXdWarLDamp3:-KaGgd26eXdWarLDamp4:b-1fpl5h) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/79c28d7f301db930c0737cc06fd6ade527cb4c27/app/helpers/mapMarkers.js#L41)):*
> ```JavaScript
>         iconUrl: errorImageUrl,
>     }, defaultProperties
> ));
> ```

new line + just thinking - shouldn't all files be either `*.jsx` or `*.js`? Or there is some convention I'm not aware of?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-:-KaGhG2Ay1GH2-14qyCG:b-yp83i4)*

**Comment by ajakubo1** [comment]
@lechup yeah!

There's a webpack tutorial regarding this:

http://survivejs.com/webpack/introduction/

I totally recommend that (thought author updated it recently to using beta version of webpack and some libraries error-out :D).

The idea which this guy has, is to make sure that we are not loading some junk automatically, and so that at a first glance we know what is the structure of project which we load. This also agrees with Zen of Python rule, where 'explicit is better then implicit'. I know we're dealing with js here, but it's a decent rule to follow :).

btw. I did browsed the mockup you refered to, I didn't add any buttons or space for charts, as we're not serving that yet :). Because of that I didn't add any routing library (thought that it might be out-of-scope for that PR).

**Comment by ajakubo1** [comment]
@lechup - I think you can take a look now, and if it's looking OK, we can finally merge with master.

So basically, as of now, if you update the station API to handle get filtering via NE, SW points, then we can have the stations on the map with pollution levels. 

This last metering value per station should be serialized as ``value`` (let me know if you serialize it under something else, as I'd have to refactor some code in order for this to work with frontend).

After the merge, I'll take a look at ``Victory`` lib.

**Comment by ajakubo1** [comment]
Oh, actually - that's not 100% right, as I input some dummy-data after fetch is done, no matter the response :).

**Comment by lechup** [comment]
Generally ok, we need some base to work on ;)

---

Reviewed 3 of 8 files at r5, 1 of 2 files at r6, 3 of 4 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[package.json, line 36 at r8](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KcHcRKPtjsNw-qgLufo:-KcHcRKQPCz_dI7CPGAO:bx30pcd) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/3c4d3447aca3e09892e0033bc453515706498399/package.json#L36)):*
> ```JSON
>     "enzyme": "^2.6.0",
>     "extract-text-webpack-plugin": "^1.0.1",
>     "fetch-mock": "^5.8.1",
> ```

JS does not have generic mock library like python?  Shouldn't all mocks be grouped in packages.json with all test related libraries? Just asking I do not have the foggies idea ;)

---

*[app/request.js, line 4 at r8](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KcHcwa4Nvsz0d0Dh5tS:-KcHcwa4Nvsz0d0Dh5tT:b-cuj1bp) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/3c4d3447aca3e09892e0033bc453515706498399/app/request.js#L4)):*
> ```JavaScript
> import queryString from 'query-string';
> 
> export const FAKE_DOMAIN = 'http://fakedomain.com/';
> ```

FAKE_DOMAIN is used in tests? Do we have API_URL somewhere? Hm... Maybe it should have deault of '' but we should be able to override it while setting environment variable?

---

*[app/actions/index.js, line 29 at r8](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KcHeU0AKdUwbMSxQSWE:-KcHeU0BPLemds3PWVVI:b-i0ylbp) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/3c4d3447aca3e09892e0033bc453515706498399/app/actions/index.js#L29)):*
> ```JavaScript
>         dispatch(invalidateLocationData());
>         dispatch(fetchDataForLocation(northEast, southWest));
>         return getAPI(API_GET_STATION_DATA, {
> ```

I'm not sure how it will be parsed but it should be something like here: https://github.com/djangonauts/django-rest-framework-gis#inbboxfilter

---

*[app/actions/index.js, line 40 at r8](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KcHe92y8yfudqWHFeb2:-KcHe92y8yfudqWHFeb3:b1ovhkq) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/3c4d3447aca3e09892e0033bc453515706498399/app/actions/index.js#L40)):*
> ```JavaScript
>                             position: [52.229, 21.032],
>                             description: "This marker should be blue",
>                             value: null
> ```

I plan to provide all data from Metering model in 'last_metering' key, 

---

*[app/components/PollutionMap.jsx, line 17 at r8](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KcHezETfwm5QvLHNcEc:-KcHezEUsYROQ0sPy4yJ:bt5qydy) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/3c4d3447aca3e09892e0033bc453515706498399/app/components/PollutionMap.jsx#L17)):*
> ```JSX
> 
>         this.state = {
>             mapCenter: [52.229, 21.011],
> ```

From my experience it is better to keep bouding box instead of map center in state. But if we do not plan to provide urls that should show same results on different resolutions for now it's ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-:-KcHfoShppVZ2Z-CNIB8:bj5zqoa)*

**Comment by ajakubo1** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[package.json, line 36 at r8](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KcHcRKPtjsNw-qgLufo:-KcHp-uCBvTVZhXazqm5:b-hw4hhu) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/3c4d3447aca3e09892e0033bc453515706498399/package.json#L36)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

JS does not have generic mock library like python?  Shouldn't all mocks be grouped in packages.json with all test related libraries? Just asking I do not have the foggies idea ;)
</blockquote></details>

Nope, it doesn't :). Hence the ``leftpad`` crisis :D.

Actually - I've updated packages.json via ``npm install --save-dev <package_name>`` - so that might cause some chaos in library listings we have :). I can rearrange them, but I don't think that's a thing :D.

---

*[webpack.config.js, line 9 at r2](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KaGbaTQ8yGc5TMbCUvb:-KcHoe7NFL3MV6xEux4M:b-t6w38j) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/79c28d7f301db930c0737cc06fd6ade527cb4c27/webpack.config.js#L9)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

This is correct way of doing it? I'm using import './node_modules/whatever/file.css' and it is magicaly added by css-loader.

The same with images only by file loader?

```
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                query: {
                    presets: ['es2015', 'react', 'stage-0']
                }
            },
            {
                test: /\.less$/,
                loader: 'style!css!postcss-loader!less-loader',
            },
            {
                test: /\.scss/,
                loader: 'style!css!postcss-loader!sass-loader',
            },
            {
                test: /\.css$/,
                loader: 'style!css!postcss-loader',
            },
            {
              test: /\.(png|jpg|gif|svg)$/,
              loader: "file-loader?name=[path][name].[ext]?[hash]"
            }
        ]
    },
```

Should I read something? :)
</blockquote></details>

Haven't responded here - I was basing the configuration on this tutorial: http://survivejs.com/webpack/introduction/

---

*[app/request.js, line 4 at r8](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KcHcwa4Nvsz0d0Dh5tS:-KcHnhslRngCcgOxM6oM:b51lyn8) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/3c4d3447aca3e09892e0033bc453515706498399/app/request.js#L4)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

FAKE_DOMAIN is used in tests? Do we have API_URL somewhere? Hm... Maybe it should have deault of '' but we should be able to override it while setting environment variable?
</blockquote></details>

Yep, its only for tests. I plan to list all API urls in urls.js.

The way I do it know - is that when I'm trying to determine the domain for tests, I add the FAKE_DOMAIN thing to url resolve (``createUrl`` function). For production and live testing, this is not added anywhere.

Sure - I like your idea, we can just pre-fill some variable here which we use all the time.

---

*[app/actions/index.js, line 29 at r8](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KcHeU0AKdUwbMSxQSWE:-KcHnVujYU7CUrFON9hK:b-e9t6ta) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/3c4d3447aca3e09892e0033bc453515706498399/app/actions/index.js#L29)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

I'm not sure how it will be parsed but it should be something like here: https://github.com/djangonauts/django-rest-framework-gis#inbboxfilter
</blockquote></details>

Example url in this configuration: /station/northEast=LatLng%2852.24378%2C%2020.98251%29&southWest=LatLng%2852.16456%2C%2020.86338%29

---

*[app/actions/index.js, line 40 at r8](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KcHe92y8yfudqWHFeb2:-KcHnL9O4NXFXYdaJfAU:bs5eiit) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/3c4d3447aca3e09892e0033bc453515706498399/app/actions/index.js#L40)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

I plan to provide all data from Metering model in 'last_metering' key, 
</blockquote></details>

good to know :). I'll swap the name then.

---

*[app/components/PollutionMap.jsx, line 17 at r8](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KcHezETfwm5QvLHNcEc:-KcHmII5Jw-l0_l7QWgl:blgtwo6) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/3c4d3447aca3e09892e0033bc453515706498399/app/components/PollutionMap.jsx#L17)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

From my experience it is better to keep bouding box instead of map center in state. But if we do not plan to provide urls that should show same results on different resolutions for now it's ok.
</blockquote></details>

I need to have a map center here, as it's an argument I'm passing during render. And re-render :). I was thinking of adding a bounding box here, but came to a conclusion that I need it only when I fetch for station data, so - why bother saving it anywhere?

---

*[app/helpers/mapMarkers.js, line 41 at r2](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KaGgd26eXdWarLDamp3:-KcHmgoL2XceTdsxEIsQ:b-6g3ljf) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/79c28d7f301db930c0737cc06fd6ade527cb4c27/app/helpers/mapMarkers.js#L41)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

new line + just thinking - shouldn't all files be either `*.jsx` or `*.js`? Or there is some convention I'm not aware of?
</blockquote></details>

nope. *.jsx are the components which are using html tags inside. No need to name everything either js or jsx.

New lines are my nemesis :3. I should really enable eslint support at some time in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15)*

**Comment by lechup** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[package.json, line 36 at r8](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KcHcRKPtjsNw-qgLufo:-KcI46uNb1cNlcThDRGx:b5dxvll) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/3c4d3447aca3e09892e0033bc453515706498399/package.json#L36)):*
<details><summary><i>Previously, ajakubo1 (Adam Jakubowski) wrote…</i></summary><blockquote>

Nope, it doesn't :). Hence the ``leftpad`` crisis :D.

Actually - I've updated packages.json via ``npm install --save-dev <package_name>`` - so that might cause some chaos in library listings we have :). I can rearrange them, but I don't think that's a thing :D.


</blockquote></details>

Ok, leave it like that. :lgtm_strong: 

---

*[app/request.js, line 4 at r8](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KcHcwa4Nvsz0d0Dh5tS:-KcI-XYU5o4NQTpqbz4a:bow3u47) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/3c4d3447aca3e09892e0033bc453515706498399/app/request.js#L4)):*
<details><summary><i>Previously, ajakubo1 (Adam Jakubowski) wrote…</i></summary><blockquote>

Yep, its only for tests. I plan to list all API urls in urls.js.

The way I do it know - is that when I'm trying to determine the domain for tests, I add the FAKE_DOMAIN thing to url resolve (``createUrl`` function). For production and live testing, this is not added anywhere.

Sure - I like your idea, we can just pre-fill some variable here which we use all the time.
</blockquote></details>

Of course I mean `API_URL` not `FAKE_DOMAIN`, we could inject it in `docker-compose.yml` if we need to.

---

*[app/actions/index.js, line 37 at r8](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KcI31kqmLPUVf6ujtWg:-KcI31krJ6Uenenk0sLT:b-bip9le) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/3c4d3447aca3e09892e0033bc453515706498399/app/actions/index.js#L37)):*
> ```JavaScript
>                         // TODO it should have data from repsonse
>                         {
>                             type: METRIC_TYPES.PM10,
> ```

Hm.. what is type for? We have such field in API, but it's  HW version of station not `METRIC_TYPE`...

---

*[app/actions/index.js, line 40 at r8](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KcHe92y8yfudqWHFeb2:-KcI2MXml3qZm5ucLDyY:bn55ohg) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/3c4d3447aca3e09892e0033bc453515706498399/app/actions/index.js#L40)):*
<details><summary><i>Previously, ajakubo1 (Adam Jakubowski) wrote…</i></summary><blockquote>

good to know :). I'll swap the name then.
</blockquote></details>

It will be rather `last_metering.pm10` or `last_metering.pm25`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15)*

**Comment by ajakubo1** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[package.json, line 36 at r8](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KcHcRKPtjsNw-qgLufo:-KcII6Txnqw47YMmHXgn:b-896fix) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/3c4d3447aca3e09892e0033bc453515706498399/package.json#L36)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

Ok, leave it like that. :lgtm_strong: 
</blockquote></details>

Done.

---

*[app/actions/index.js, line 37 at r8](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-KcI31kqmLPUVf6ujtWg:-KcIIFSPffK0w5L0u0vg:b-ahds3b) ([raw file](https://github.com/enviromonitor/enviromonitorfrontend/blob/3c4d3447aca3e09892e0033bc453515706498399/app/actions/index.js#L37)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

Hm.. what is type for? We have such field in API, but it's  HW version of station not `METRIC_TYPE`...
</blockquote></details>

My workaround on... well... Type of metric sent :). I'll have to change it somehow based on your comment ``last_metering.pm10``, ``last_metering.pm25``. I use that type later on to figure out what color of marker should I use on the map (I didn't remove that decision code, as - based on our discussion - I'm not 100% sure how do we represent live-data on the map).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15)*

**Comment by lechup** [comment]
:lgtm: let's merge it to master!

---

Reviewed 9 of 9 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorfrontend/15#-:-KcMXiAG5mdfp4xocDDh:b4at4v3)*

**Review by lechup — APPROVED** [review]

**Pull request merged**
